### ISSUE TITLE
Jest throws an error when rendering a floatingLabel

### ISSUE THREAD

**Issue by Slessi** [GeekyAnts/NativeBase#1762]
## react-native, react and native-base version
```
"native-base": "^2.3.5",
"react": "16.0.0",
"react-native": "0.51.0"
```
## Expected behaviour
Test runs without throwing an error

## Actual behaviour
Test throws the following error

```
/Users/user1/Desktop/dev/native-base-floating-label-issue/node_modules/jest-runtime/build/index.js:538
    const wrapper = this._environment.runScript(transformedFile.script)[
                                                                       ^

TypeError: Cannot read property 'Object.<anonymous>' of null
    at Runtime._execModule (/Users/®/Desktop/dev/native-base-floating-label-issue/node_modules/jest-runtime/build/index.js:538:72)
    at Runtime.requireModule (/Users/user1/Desktop/dev/native-base-floating-label-issue/node_modules/jest-runtime/build/index.js:330:14)
    at Runtime.requireModuleOrMock (/Users/user1/Desktop/dev/native-base-floating-label-issue/node_modules/jest-runtime/build/index.js:410:19)
    at Function.bezier (/Users/user1/Desktop/dev/native-base-floating-label-issue/node_modules/react-native/Libraries/Animated/src/Easing.js:223:13)
    at ease (/Users/user1/Desktop/dev/native-base-floating-label-issue/node_modules/react-native/Libraries/Animated/src/Easing.js:94:14)
    at TimingAnimation._easing (/Users/user1/Desktop/dev/native-base-floating-label-issue/node_modules/react-native/Libraries/Animated/src/Easing.js:257:10)
    at TimingAnimation.onUpdate (/Users/user1/Desktop/dev/native-base-floating-label-issue/node_modules/react-native/Libraries/Animated/src/animations/TimingAnimation.js:129:22)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
npm ERR! Test failed.  See above for more details.
```

## Steps to reproduce (code snippet or screenshot)
Was filed by someone else here facebook/jest#5205 but it was closed as it did not appear to be a jest specific issue 

There is a repo to reproduce here: https://github.com/tylermurry/native-base-floating-label-issue
Alternatively, the following test snippet reproduces the error

```js
import 'react-native';
import React from 'react';
import renderer from 'react-test-renderer';
import {Item} from "native-base";
// require('bezier');  // Uncommenting this fixes this issue

test('someTest', () => {
    renderer.create(<Item floatingLabel />);
});
```

## Any other additional info which would help us debug the issue quicker.

Adding `require('bezier');` before the test resolves the issue

**Comment by bruno-campos** [comment]
This seems to be a bug with jest and react-native Animated. Related issue: https://github.com/facebook/jest/issues/4359

I was able to get rid of it by using `jest.jest.useFakeTimers();` where testing components that uses the floatingLabel.

**Comment by SupriyaKalghatgi** [comment]
@Slessi Can you check with this work around?

**Comment by Slessi** [comment]
@SupriyaKalghatgi I confirm that `jest.useFakeTimers()` works
