### ISSUE TITLE
[mocha test] SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by devhyunjae** [GeekyAnts/NativeBase#21]
original source,

```javascript
import React from 'react';
import {
  View,
  Text,
} from 'react-native';

const ChatList = () => (
  <View>
    <Text>Hello world</Text>
  </View>
);

export default ChatList;
```

mocha test runs fine.

after i added this code,

`import { Container, Header, Content, Footer, Title } from 'native-base';`

and run mocha test,

it throws 

> mocha --require react-native-mock/mock.js --compilers js:babel-core/register src/**/*.t
est.js --watch

```
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Module._extensions..js (module.js:405:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/canna/my-projects/

mshopbang/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (ChatList.js:6:1)
    at Module._compile (module.js:398:26)
    at loader (/Users/canna/my-projects/mshopbang/node_modules/babel-register/lib/node.js
:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/canna/my-projects/
mshopbang/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

**Comment by jstoeffler** [comment]
Did you solve this issue? If yes can you share your solution?

**Comment by sospedra** [comment]
How you fix it?

**Comment by quangrau** [comment]
Still got this problem. After read a great blog about testing with mocha + enzyme + react-native. [here](https://blog.addjam.com/testing-react-native-with-mocha-and-enzyme-6b77cd9e52a1), but I got another error like this:

<img width="620" alt="screen shot 2017-05-17 at 5 26 40 pm" src="https://cloud.githubusercontent.com/assets/3326521/26149856/18ee8952-3b26-11e7-8208-32c1cd5b7a83.png">

**Comment by thg303** [comment]
with `version 2.3.3` still problem exists.

**Comment by IbraheemAlSaady** [comment]
I'm having the same problem right now, any solution for that?
