### ISSUE TITLE
code Z_BUF_ERROR npm ERR! errno -5 in installing native base

### ISSUE THREAD

**Issue by im-noob** [GeekyAnts/NativeBase#2319]
## i got the error in when im tring to installing native base...
i have gone through https://github.com/GeekyAnts/NativeBase#4-getting-started

but when i fire the command npm install native-base --save

i get this error 
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\noob\AppData\Roaming\npm-cache\_logs\2018-10-01T07_36_41_947Z-debug.log

https://i.imgur.com/PedZOkj.png

### Here is the complete log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'native-base',
1 verbose cli   '--save' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose npm-session 6604468b8b80082b
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/native-base 769ms (from cache)
8 http fetch GET 304 https://registry.npmjs.org/native-base/-/native-base-2.8.0.tgz 390ms (from cache)
9 silly fetchPackageMetaData error for native-base@latest zlib: unexpected end of file
10 timing stage:rollbackFailedOptional Completed in 9ms
11 timing stage:runTopLevelLifecycles Completed in 9609ms
12 verbose stack ZlibError: zlib: unexpected end of file
12 verbose stack     at Zlib.(anonymous function).onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\minizlib\index.js:131:21)
12 verbose stack     at Unzip.write (C:\Program Files\nodejs\node_modules\npm\node_modules\minizlib\index.js:255:31)
12 verbose stack     at Unzip.flush (C:\Program Files\nodejs\node_modules\npm\node_modules\minizlib\index.js:222:10)
12 verbose stack     at Unzip.end (C:\Program Files\nodejs\node_modules\npm\node_modules\minizlib\index.js:229:10)
12 verbose stack     at Object.end (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:415:21)
12 verbose stack     at PassThrough.onend (_stream_readable.js:628:10)
12 verbose stack     at Object.onceWrapper (events.js:273:13)
12 verbose stack     at PassThrough.emit (events.js:187:15)
12 verbose stack     at endReadableNT (_stream_readable.js:1085:12)
12 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
13 verbose cwd C:\fr2\react\LibSearch\WithBaseTry2
14 verbose Windows_NT 10.0.10240
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "native-base" "--save"
16 verbose node v10.9.0
17 verbose npm  v6.2.0
18 error code Z_BUF_ERROR
19 error errno -5
20 error zlib: unexpected end of file
21 verbose exit [ -5, true ]

```

### node:v10.9.0 , npm:6.2.0,  expo CLI:2.2.0 version 

##package.json

```
{
  "expo": {
    "name": "WithBaseTry2",
    "description": "This project is really great.",
    "slug": "WithBaseTry2",
    "privacy": "public",
    "sdkVersion": "30.0.0",
    "platforms": ["ios", "android"],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    }
  }
}


```

**Comment by shahriar556** [comment]
npm cache clean --force
