### ISSUE TITLE
Unable to resolve module `./theme/variables/platform`

### ISSUE THREAD

**Issue by rodyyaacoub** [GeekyAnts/NativeBase#2618]
"native-base": "^2.12.0",
"react": "16.6.3",
"react-native": "0.58.6",

npm install on my project, react-native link and then run the project to see this error..

App throws a red screen with the error

Error: Unable to resolve module `./theme/variables/platform` from `C:\Sowlutions\LastFm\node_modules\native-base\dist\src\index.js`: The module `./theme/variables/platform` could not be found from `C:\Sowlutions\LastFm\node_modules\native-base\dist\src\index.js`. Indeed, none of these files exist:
  * `C:\Sowlutions\LastFm\node_modules\native-base\dist\src\theme\variables\platform(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `C:\Sowlutions\LastFm\node_modules\native-base\dist\src\theme\variables\platform\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (C:\Sowlutions\LastFm\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\Sowlutions\LastFm\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\Sowlutions\LastFm\node_modules\metro\src\node-haste\DependencyGraph.js:273:16)
    at Object.resolve (C:\Sowlutions\LastFm\node_modules\metro\src\lib\transformHelpers.js:261:42)
    at dependencies.map.result (C:\Sowlutions\LastFm\node_modules\metro\src\DeltaBundler\traverseDependencies.js:391:31)    at Array.map (<anonymous>)
    at resolveDependencies (C:\Sowlutions\LastFm\node_modules\metro\src\DeltaBundler\traverseDependencies.js:388:18)
    at C:\Sowlutions\LastFm\node_modules\metro\src\DeltaBundler\traverseDependencies.js:261:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Sowlutions\LastFm\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)

**Comment by SupriyaKalghatgi** [comment]
Can you clone from https://github.com/GeekyAnts/NativeBase-KitchenSink and verify?

**Comment by SupriyaKalghatgi** [comment]
Closing this today in case of no response
