### ISSUE TITLE
v3.0.6: Unable to resolve styled-components/native on IOS/Android emulator after upgrading from 2.15

### ISSUE THREAD

**Issue by emclab** [GeekyAnts/NativeBase#3892]
**Describe the bug**
After upgrading to 3.0.6 from 2.15, launching the React Native 0.64 app on IOS emulator/Android emulator causes an error of unresolved module.

"Unable to resolve module styled-components/native from .../node_modules/native-base/src/components/composites/Tag/index.tsx: styled-components/native could not be found within the project or in these directories: node-modules/native-base/node_modules.

Here is the detail of error on console:
 ```
 BUNDLE  ./index.js

error: Error: Unable to resolve module styled-components/native from C:\D\code\js\xyz_app4\node_modules\native-base\src\components\primitives\Text\index.tsx: styled-components/native could not be found within the project or in these directories:
  node_modules\native-base\node_modules
  node_modules
  ..\node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | import React, { memo, forwardRef, useRef } from 'react';
  2 | import { Text as NativeText } from 'react-native';
> 3 | import styled from 'styled-components/native';  //<<=== error
    |                     ^
  4 | import {
  5 |   color,
  6 |   position,
    at ModuleResolver.resolveDependency (C:\D\code\js\xyz_app4\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:234:15)
    at DependencyGraph.resolveDependency (C:\D\code\js\xyz_app4\node_modules\metro\src\node-haste\DependencyGraph.js:413:43)
    at Object.resolve (C:\D\code\js\xyz_app4\node_modules\metro\src\lib\transformHelpers.js:317:42)
    at resolve (C:\D\code\js\xyz_app4\node_modules\metro\src\DeltaBundler\traverseDependencies.js:629:33)
    at C:\D\code\js\xyz_app4\node_modules\metro\src\DeltaBundler\traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (C:\D\code\js\xyz_app4\node_modules\metro\src\DeltaBundler\traverseDependencies.js:644:33)
    at C:\D\code\js\xyz_app4\node_modules\metro\src\DeltaBundler\traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\D\code\js\xyz_app4\node_modules\metro\src\DeltaBundler\traverseDependencies.js:137:24)
 BUNDLE  ./index.js

error: Error: Unable to resolve module styled-components/native from C:\D\code\js\xyz_app4\node_modules\native-base\src\components\composites\Tag\index.tsx: styled-components/native could not be found within the project or in these directories:
  node_modules\native-base\node_modules
  node_modules
  ..\node_modules
```

And there is indeed no styled-components under those subdirectgories. The same error appears on both IOS/Android emulator after upgrading to 3.0.6

**Expected behaviour**
App launch without error.

**CodeSandBox/Snack link**
It would be easier for us to debug if you can reproduce the error in a codesandbox link or a snack link. You can use the [codesandbox template](https://codesandbox.io/s/native-base-v3-template-mq6ox)/[snack template](https://snack.expo.io/@mdrehman/nativebase-template).

**Screenshots**

**Platform**
 - NativeBase version  3.0.6
 - Device: [e.g. iPhone6] IOS/Android emulator
 - OS: [e.g. iOS8.1] IOS/Android
 - Browser version [e.g. 22]
 - React Native version [e.g. 0.64] 0.64
 - Expo sdk version [e.g. 41]
 - node [e.g. 14.16.1], 14,17.x
 - yarn or npm [e.g. 6.1] 1.22

**Additional information**

Here is screen shot on android emulator 
![Capture](https://user-images.githubusercontent.com/946013/127193972-36f2fc13-ea46-4f5d-b914-986c50c5c3ed.JPG)

1. Add any other context about the problem here.
2. Is the bug present in both iOS and Android or in any one of them?
3. If you want your issue to be looked at quicker, please attach a snack reproducible with your issue. Makes it easier for us!

**Comment by emclab** [comment]
Tried to install styled-components under /node_modules/native-base/ and failed. here is the error:

```
$ bob build
ℹ Building target commonjs
ℹ Cleaning up previous build at lib\commonjs
ℹ Compiling 477 files in src with babel
bob.js build

build files for publishing

Options:
  --help     Show help                             [boolean]  --version  Show version number                   [boolean]
SyntaxError: C:\D\code\js\xyz_app4\node_modules\native-base\src\index.tsx: Unexpected token, expected "," (2:12)        

  1 | export default {
> 2 |   multiply(a: number, b: number) {
    |             ^
  3 |     return Promise.resolve(a * b);
  4 |   },
  5 | };
    at Parser._raise (C:\D\code\js\xyz_app4\node_modules\native-base\node_modules\@babel\parser\lib\index.js:788:17)    
    at Parser.raiseWithData (C:\D\code\js\xyz_app4\node_modules\native-base\node_modules\@babel\parser\lib\index.js:781:17)
    at Parser.raise (C:\D\code\js\xyz_app4\node_modules\native-base\node_modules\@babel\parser\lib\index.js:742:17)     
    at Parser.unexpected (C:\D\code\js\xyz_app4\node_modules\native-base\node_modules\@babel\parser\lib\index.js:9929:16)
    at Parser.expect (C:\D\code\js\xyz_app4\node_modules\native-base\node_modules\@babel\parser\lib\index.js:9903:28)   
    at Parser.parseBindingList (C:\D\code\js\xyz_app4\node_modules\native-base\node_modules\@babel\parser\lib\index.js:10380:14)
    at Parser.parseFunctionParams (C:\D\code\js\xyz_app4\node_modules\native-base\node_modules\@babel\parser\lib\index.js:13322:24)
    at Parser.parseMethod (C:\D\code\js\xyz_app4\node_modules\native-base\node_modules\@babel\parser\lib\index.js:11966:10)
    at Parser.parseObjectMethod (C:\D\code\js\xyz_app4\node_modules\native-base\node_modules\@babel\parser\lib\index.js:11895:19)
    at Parser.parseObjPropValue (C:\D\code\js\xyz_app4\node_modules\native-base\node_modules\@babel\parser\lib\index.js:11928:23) {
  loc: Position { line: 2, column: 12 },
  pos: 29,
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'UnexpectedToken'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by darrylyoung** [comment]
I know this doesn't help but I'd like to add that I've also had this problem and, as a result, I'm stuck on `2.15.2`. I'm not sure what else to try — I've cleared watchman caches and node_modules as well as run [`react-native-clean-project`](https://github.com/pmadruga/react-native-clean-project), which basically cleans **everything**. If it helps, I'm using Hermes and have been trying on an iOS 14.5 Simulator.

**Comment by darrylyoung** [comment]
Did you find a solution here, @emclab? I'm still getting the same issue if I try.

**Comment by mrcarjul** [comment]
You need to install peerDependencies https://docs.nativebase.io/install-rn#install-dependencies

**Comment by makkarMeenu** [comment]
Also, we have removed styled-components as a dependency in NativeBase.
