### ISSUE TITLE
Eject Theme Command not working

### ISSUE THREAD

**Issue by MuhammadAhmed1994** [GeekyAnts/NativeBase#4028]
I am unable to eject the theme

Native base version: 3.1.0

Command: node node_modules/native-base/ejectTheme.js

Error: Cannot find module '/Users/ahmed/Desktop/f3-git-repos/bmc/node_modules/native-base/ejectTheme.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by makkarMeenu** [comment]
@MuhammadAhmed1994 Can you please specify the steps to reproduce this error?
