### ISSUE TITLE
2 errors about fowardRef render

### ISSUE THREAD

**Issue by Amitkahlon** [GeekyAnts/NativeBase#4109]
** Before reporting this bug, please...**

1. Check the latest documentation: https://docs.nativebase.io/
2. Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
3. Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
4. Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
5. For discussion purpose make use of NativeBase discord: https://discord.gg/TSgCw2UPmb

**Describe the bug**
2 big errors when lunching the project on android studio.
```
Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
at node_modules\react-native\Libraries\LogBox\LogBox.js:173:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react\cjs\react.development.js:315:4 in printWarning
at node_modules\react\cjs\react.development.js:287:16 in error
at node_modules\react\cjs\react.development.js:1424:13 in forwardRef
at node_modules\native-base\src\components\primitives\Hidden\index.tsx:79:20 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at node_modules\native-base\src\components\primitives\index.ts:61:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at node_modules\native-base\src\components\composites\Alert\AlertIcon.tsx:2:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at node_modules\native-base\src\components\composites\Alert\index.tsx:1:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at node_modules\native-base\src\components\composites\index.ts:12:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at node_modules\native-base\src\index.tsx:7:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at App.tsx:2:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at node_modules\expo\AppEntry.js:3:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at node_modules\metro\src\lib\polyfills\require.js:201:44 in guardedLoadModule
at http://192.168.1.107:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:223410:3 in global code
```

```
Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
at node_modules\react-native\Libraries\LogBox\LogBox.js:173:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react\cjs\react.development.js:315:4 in printWarning
at node_modules\react\cjs\react.development.js:287:16 in error
at node_modules\react\cjs\react.development.js:1424:13 in forwardRef
at node_modules\native-base\src\components\composites\Skeleton\SkeletonCircle.tsx:12:20 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at node_modules\native-base\src\components\composites\Skeleton\index.tsx:3:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at node_modules\native-base\src\components\composites\index.ts:37:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at node_modules\native-base\src\index.tsx:7:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at App.tsx:2:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at node_modules\expo\AppEntry.js:3:0 in <global>
at node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
at node_modules\metro\src\lib\polyfills\require.js:201:44 in guardedLoadModule
at http://192.168.1.107:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:223410:3 in global code
```

**To Reproduce**
I installed a new typescript react project with expo, installed native base and lunched the project

**Platform**

- NativeBase version [3.2.0]
- Device: [Pixel 2 API 30]
- Android

everything is latest version

in addition i think this problem also occurs also in react javascript but its show it as a yellow error

**Comment by leoparis89** [comment]
I get these errors too:
```

    Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?

      at printWarning (node_modules/react/cjs/react.development.js:220:30)
      at error (node_modules/react/cjs/react.development.js:196:5)
      at forwardRef (node_modules/react/cjs/react.development.js:1377:9)
      at Object.<anonymous> (node_modules/native-base/lib/commonjs/components/primitives/Hidden/index.js:1:2524)
```

and
```

  Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?

      at printWarning (node_modules/react/cjs/react.development.js:220:30)
      at error (node_modules/react/cjs/react.development.js:196:5)
      at forwardRef (node_modules/react/cjs/react.development.js:1377:9)
      at Object.<anonymous> (node_modules/native-base/lib/commonjs/components/composites/Skeleton/SkeletonCircle.js:1:1270)

```

Is there a workaround at the moment ?

**Comment by daomtthuan** [comment]
i think this warning appears because `forwardRef render function` needs `props` and `ref` as 2 parameters, but in 2 components:
- `Hidden` at `native-base\src\components\primitives\Hidden\index.tsx`
- `SkeletonCircle` at `native-base\src\components\composites\Skeleton\SkeletonCircle.tsx`
`forwardRef render function` missing `ref` param

I think just add `ref`
`const SkeletonCircle = ({ children, ...props }: ISkeletonProps)` => `const SkeletonCircle = ({ children, ...props }: ISkeletonProps, ref)`
add
`export function Hidden({ children, ...props }: IHiddenProps)` => `export function Hidden({ children, ...props }: IHiddenProps, ref)`

This is a temporary solution, hopefully the next version, the library will have the solutions

**Comment by santigp258** [comment]
> i think this warning appears because `forwardRef render function` needs `props` and `ref` as 2 parameters, but missing ref param in 2 components:
> 
> * `Hidden` at `native-base\src\components\primitives\Hidden\index.tsx`
> * `SkeletonCircle` at `native-base\src\components\composites\Skeleton\SkeletonCircle.tsx`
>   `forwardRef render function`
> 
> I think just add `ref`
> `const SkeletonCircle = ({ children, ...props }: ISkeletonProps)` => `const SkeletonCircle = ({ children, ...props }: ISkeletonProps, ref)`
> add
> `export function Hidden({ children, ...props }: IHiddenProps)` => `export function Hidden({ children, ...props }: IHiddenProps, ref)`
> 
> This is a temporary solution, hopefully the next version, the library will have the solutions

Yeah, solve the issue. I hope this be fixed in the next version

**Comment by trajano** [comment]
https://github.com/GeekyAnts/NativeBase/pull/4096 tries to resolve this.

**Comment by sXakil** [comment]
Faced this issue too, had to roll back to v3.1. I was using a custom drawer component in react-navigation, no idea if or why this caused the issue.

**Comment by gold-olar** [comment]
> i think this warning appears because `forwardRef render function` needs `props` and `ref` as 2 parameters, but missing ref param in 2 components:
> 
> * `Hidden` at `native-base\src\components\primitives\Hidden\index.tsx`
> * `SkeletonCircle` at `native-base\src\components\composites\Skeleton\SkeletonCircle.tsx`
> 
> I think just add `ref` `const SkeletonCircle = ({ children, ...props }: ISkeletonProps)` => `const SkeletonCircle = ({ children, ...props }: ISkeletonProps, ref)` add `export function Hidden({ children, ...props }: IHiddenProps)` => `export function Hidden({ children, ...props }: IHiddenProps, ref)`
> 
> This is a temporary solution, hopefully the next version, the library will have the solutions

This temporary solution works, Thanks 👍🏾.
I hope the next version fixes this ...

**Comment by trajano** [comment]
The 3.2.1.rc-1 actually fixes it.

**Comment by intergalacticspacehighway** [comment]
This has been fixed in 3.2.1. Let us know if you face any issues!
