### ISSUE TITLE
Hidden and SkeletonCircle uses forwardRef with only one parameter

### ISSUE THREAD

**Issue by trajano** [GeekyAnts/NativeBase#4121]
When importing native-base in jest the following warnings appear.

    console.error
      Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?

      at printWarning (node_modules/react/cjs/react.development.js:315:30)
      at error (node_modules/react/cjs/react.development.js:287:5)
      at forwardRef (node_modules/react/cjs/react.development.js:1424:9)
      at Object.<anonymous> (node_modules/native-base/lib/commonjs/components/primitives/Hidden/index.tsx:79:21)

    console.error
      Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?

      at printWarning (node_modules/react/cjs/react.development.js:315:30)
      at error (node_modules/react/cjs/react.development.js:287:5)
      at forwardRef (node_modules/react/cjs/react.development.js:1424:9)
      at Object.<anonymous> (node_modules/native-base/lib/commonjs/components/composites/Skeleton/SkeletonCircle.tsx:12:21)

**Comment by trajano** [comment]
dup #4109
