### ISSUE TITLE
`React.createElement: type is invalid` when running tests in nx workspace project

### ISSUE THREAD

**Issue by aqos156** [GeekyAnts/NativeBase#4431]
**Describe the bug**
When a test is run under nx workspace react-native app the tests return multiple warnings `React.createElement: type is invalid...`

**To Reproduce**
Steps to reproduce the behaviour:

1. Create nx workspace `npx create-nx-workspace@latest my-nx-workspace --preset=react-native --package-manager=yarn`
2. Fill in application name to `myapp` when asked and select no for cloud builds
2. `cd my-nx-workspace`
3.  Install nativebase and add any compoennts into App.tsx in `apps/myapp`
3. `yarn nx test myapp`
4. See errors

**Expected behaviour**
When running a test using `yarn nx test myapp` the tests finish fine without any redundant warnings/errors

**CodeSandBox/Snack link**
It would be easier for us to debug if you can reproduce the error in a codesandbox link or a snack link. You can use the [codesandbox template](https://codesandbox.io/s/native-base-v3-template-mq6ox)/[snack template](https://snack.expo.io/@mdrehman/nativebase-template).

**Logs**
```
╰─$ nx test myapp

> nx run myapp:test 
  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at questionIconPath.tsx:6.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/questionIconPath.tsx:9:9)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at questionIconPath.tsx:11.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/questionIconPath.tsx:14:9)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at questionIconPath.tsx:16.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/questionIconPath.tsx:16:65)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at questionIconPath.tsx:5.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/questionIconPath.tsx:5:3)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Check.tsx:9.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Check.tsx:9:23)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Check.tsx:8.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Check.tsx:8:5)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Chevron.tsx:9.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Chevron.tsx:9:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Chevron.tsx:10.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Chevron.tsx:10:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Chevron.tsx:8.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Chevron.tsx:8:5)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Close.tsx:14.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Close.tsx:15:9)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Info.tsx:14.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Info.tsx:14:57)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Info.tsx:15.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Info.tsx:15:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Info.tsx:16.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Info.tsx:16:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Info.tsx:8.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Info.tsx:11:21)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Minus.tsx:8.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Minus.tsx:8:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Minus.tsx:7.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Minus.tsx:7:5)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Sun.tsx:15.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Sun.tsx:15:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Sun.tsx:16.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Sun.tsx:16:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Sun.tsx:17.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Sun.tsx:17:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Sun.tsx:18.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Sun.tsx:18:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Sun.tsx:19.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Sun.tsx:19:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Sun.tsx:20.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Sun.tsx:20:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Sun.tsx:21.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Sun.tsx:21:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Sun.tsx:22.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Sun.tsx:22:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Sun.tsx:23.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Sun.tsx:23:7)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at Sun.tsx:8.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Sun.tsx:11:19)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at ThreeDots.tsx:9.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/ThreeDots.tsx:9:15)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check your code at ThreeDots.tsx:8.
        at App (/Users/user/Documents/Projekty/custom/nx-workspace/apps/myapp/src/app/App.tsx:15:64)

      at printWarning (../../node_modules/react/cjs/react.development.js:220:30)
      at error (../../node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (../../node_modules/react/cjs/react.development.js:2215:7)
      at Object.<anonymous> (../../node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/ThreeDots.tsx:8:5)

[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
```

**Platform**

- NativeBase version [3.2.2]
- Device: [testing in jest]
- OS: [-]
- Browser [-]
- Browser version [-]
- React Native version [0.62.2]
- Expo sdk version [-]
- node [17.0.2]
- yarn [1.22.17]

**Additional information**

1. Add any other context about the problem here.
2. Is the bug present in both iOS and Android or in any one of them?
3. If you want your issue to be looked at quicker, please attach a snack reproducible with your issue. Makes it easier for us!

**Comment by mayank-96** [comment]
@aqos156 Thanks for reporting, we'll look into this.

**Comment by cloudratha** [comment]
@mayank-96 any news? we are experiencing this as well.

**Comment by cloudratha** [comment]
I've been able to remove the warning by using `ts-jest` and by removing the `svg-mock` in `moduleNameMapper` in the `jest.config.js`. I realised the issues were stemming from native-base icons which are probably svg based.

What confuses me the most is the stack trace referencing a file that doesn't exists:

`node_modules/native-base/lib/commonjs/components/primitives/Icon/Icons/Sun.tsx`

`lib` only contains js files.

**Comment by tankers746** [comment]
Can you try adding a `\\` in front of the `.svg` like so:
```
  moduleNameMapper: {
    '.svg': '@nrwl/react-native/plugins/jest/svg-mock',
  },
```
```
  moduleNameMapper: {
    '\\.svg': '@nrwl/react-native/plugins/jest/svg-mock',
  },
```

**Comment by mkurczewski** [comment]
The above solutions works for me. Here's a function that you can apply to your custom library generator:

```TSX
function fixSvgModuleNameMapper(tree, root) {
  const path = joinPathFragments(root, "./jest.config.js")
  const config = tree.read(path, "utf-8")

  const svgModuleNameMapperIndex = config.indexOf(
    `".svg": "@nrwl/react-native/plugins/jest/svg-mock"`
  )

  const updatedConfig = applyChangesToString(config, [
    {
      type: ChangeType.Insert,
      index: svgModuleNameMapperIndex + 5,
      text: "$",
    },
    {
      type: ChangeType.Insert,
      index: svgModuleNameMapperIndex + 1,
      text: "\\\\",
    },
  ])

  tree.write(path, updatedConfig)
}
```

**Comment by lanceturbes** [comment]
Thank you for sharing these workarounds, everyone -- issue is still relevant. The `\\.svg$` adjustment inside `jest.config.ts`, specifically, worked for me.

**Comment by surajahmed** [comment]
Closing this issue for now. Please feel free to reopen.
