### ISSUE TITLE
fontFamily "Courier" is not a system font and has not been loaded through Font.loadAsync.

### ISSUE THREAD

**Issue by calboru** [GeekyAnts/NativeBase#4782]
### Description

happens in IOS simulator

### CodeSandbox/Snack link

react-native expo template

### Steps to reproduce

1. expo init my-app --template @native-base/expo-template
2. yarn ios

### NativeBase Version

3.3.7 and also latest alpha

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

fontFamily "Courier" is not a system font and has not been loaded through Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

- If this is a custom font, be sure to load it with Font.loadAsync.
at node_modules/expo-font/build/Font.js:27:16 in processFontFamily
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:54:4 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:117:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:213:4 in runApplication

**Comment by surajahmed** [comment]
@calboru Thanks for reporting this! `Code` component is still a work in progress. We'll try to fix this in the coming release.

**Comment by dohomi** [comment]
any update on this issue?

**Comment by Viraj-10** [comment]
Hi @dohomi, `Code` is an unreleased component.
