### ISSUE TITLE
App with NativeBase breaking after upgrading to expo 46

### ISSUE THREAD

**Issue by danielantelo** [GeekyAnts/NativeBase#5223]
### Description

App with NativeBase breaking after upgrading to expo 46

### CodeSandbox/Snack link

https://github.com/danielantelo/expo-template-reactrouter-nativebase/tree/expo-46

### Steps to reproduce

1. Launch app
2. Go to [localhost](http://localhost:19006/) on Web browser (chrome)
3. See error on console

```
Uncaught Error: Cannot find module 'react-native-web/dist/exports/StyleSheet/createCompileableStyle'
    at webpackMissingModule (useResponsiveQuery.web.ts:2:1)
    at ./node_modules/native-base/lib/module/utils/useResponsiveQuery/useResponsiveQuery.web.js (useResponsiveQuery.web.ts:2:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/native-base/lib/module/utils/useResponsiveQuery/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/native-base/lib/module/hooks/useStyledSystemPropsResolver.js (useScreenReaderEnabled.ts:36:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/native-base/lib/module/hooks/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/native-base/lib/module/components/primitives/Box/index.js (index.ts:150:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/native-base/lib/module/components/composites/AspectRatio/index.js (index.tsx:17:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/native-base/lib/module/components/composites/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/native-base/lib/module/index.js (index.tsx:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./App.tsx (App.tsx:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/expo/AppEntry.js (AppEntry.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at 1 (routing.tsx:59:1)
    at __webpack_require__ (bootstrap:789:1)
    at bootstrap:856:1

```

Working fine on IOS, just web is broken. 

### NativeBase Version

3.4.9

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by danielantelo** [comment]
Sorry if duplicates https://github.com/GeekyAnts/NativeBase/issues/5075
