### ISSUE TITLE
Support for Nextjs 12.2 and React 18.2

### ISSUE THREAD

**Issue by EuanGwd-AndDigital** [GeekyAnts/NativeBase#5249]
### Description

Not really a bug, having issues adding Native base to an existing  nextjs 12.2 app, the cli, examples and documentation seem to only refer to next12.1 and react 17

### CodeSandbox/Snack link

NA

### Steps to reproduce

1. install new create-next-app using yarn
2. follow instructions in documentation on adding to existing project
3. run yarn dev

### NativeBase Version

latest

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [X] Next

### Additional Information

Wondering if React18 is supported in nativebase as yet

**Comment by Viraj-10** [comment]
Hi @EuanGwd-AndDigital, We are looking into this issue. We will soon provide support for react 18 and next 12.

**Comment by coprocoder** [comment]
@Viraj-10 Is there any rc patch or alpha build now? Is it possible to get support for react 18 before the release of the new official version of your package?

**Comment by liebharc** [comment]
Hi @Viraj-10, my team would also be interested in this topic. I did some experiments with the current version on native-base with react 18, and it seems to work mostly. Mainly we found an issue if you put an Input in a Modal and then use the Input from a mobile device. 

Switching to Next.js 12.2 fails. Apart from the warnings which are already listed in this issue description I'm getting an error related to the  _document.js:

```
[    ] info  - Generating static pages (0/3)
Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
Error: "Document.getInitialProps()" should resolve to an object with a "html" prop set with a valid html string
    at loadDocumentInitialProps (/home/christian/Projects/nativebase-nextjs-input/node_modules/next/dist/server/render.js:680:23)
    at async renderDocument (/home/christian/Projects/nativebase-nextjs-input/node_modules/next/dist/server/render.js:763:43)
    at async renderToHTML (/home/christian/Projects/nativebase-nextjs-input/node_modules/next/dist/server/render.js:801:28)
    at async /home/christian/Projects/nativebase-nextjs-input/node_modules/next/dist/export/worker.js:251:36
    at async Span.traceAsyncFn (/home/christian/Projects/nativebase-nextjs-input/node_modules/next/dist/trace/trace.js:79:20)

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
Error: "Document.getInitialProps()" should resolve to an object with a "html" prop set with a valid html string
    at loadDocumentInitialProps (/home/christian/Projects/nativebase-nextjs-input/node_modules/next/dist/server/render.js:680:23)
    at async renderDocument (/home/christian/Projects/nativebase-nextjs-input/node_modules/next/dist/server/render.js:763:43)
    at async renderToHTML (/home/christian/Projects/nativebase-nextjs-input/node_modules/next/dist/server/render.js:801:28)
    at async /home/christian/Projects/nativebase-nextjs-input/node_modules/next/dist/export/worker.js:251:36
    at async Span.traceAsyncFn (/home/christian/Projects/nativebase-nextjs-input/node_modules/next/dist/trace/trace.js:79:20)

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: "Document.getInitialProps()" should resolve to an object with a "html" prop set with a valid html string
    at loadDocumentInitialProps (/home/christian/Projects/nativebase-nextjs-input/node_modules/next/dist/server/render.js:680:23)
    at async renderDocument (/home/christian/Projects/nativebase-nextjs-input/node_modules/next/dist/server/render.js:763:43)
    at async renderToHTML (/home/christian/Projects/nativebase-nextjs-input/node_modules/next/dist/server/render.js:801:28)
    at async /home/christian/Projects/nativebase-nextjs-input/node_modules/next/dist/export/worker.js:251:36
    at async Span.traceAsyncFn (/home/christian/Projects/nativebase-nextjs-input/node_modules/next/dist/trace/trace.js:79:20)
info  - Generating static pages (3/3)
```
My playground for this would be available under: https://github.com/liebharc/nativebase-nextjs-input

Let me know if there is anything more concrete, which would help you guys.

**Comment by Viraj-10** [comment]
Hi @EuanGwd-AndDigital, We have released `v3.4.12-alpha.1` for react-native-web 0.18 and expo SDK 46 support.

**Comment by dohomi** [comment]
@Viraj-10 the upgrade of react-native-web and expo hasn't fixed the compatibility issue with Next 12.2.x
As described above there seems to be some changes in _document and other places which breaks the Next compilation.

**Comment by liebharc** [comment]
@Viraj-10 , apologies if this doesn't belong in this discussion, but since you've mentioned 3.4.12 and react-native-web: The latest native-base with react-native-web gives an error:

`Module not found: Can't resolve 'react-native-web/dist/exports/StyleSheet/createCompileableStyle'`

Steps to reproduce:

1. git checkout https://github.com/liebharc/nativebase-nextjs-input
2. cd nativebase-nextjs-input
3. pnpm run dev 
4. visit localhost:3000

**Comment by dohomi** [comment]
@liebharc 3.4.12 includes not changes made in v3.4.12-alpha.1 - thats quite confusing but the PR is not merged into master yet. @Viraj-10 it might be better to use a different name for PR pre-releases which are not connecting to SEMVER versioning because me and a few other users bumped into the same issue that we though 3.4.12 will include the alpha.1 changes.

**Comment by liebharc** [comment]
@dohomi , ah thanks for the clarification. I was able to get this combination running:

- native-base 3.4.12-alpha.1
- react-native-web: 0.18.7
- next: 12.2.1

For this I removed the native base adapter for the moment and changed my _document.js to:

```
import { getInitialProps } from '@expo/next-adapter/document';
import Document, { Html, Head, Main, NextScript } from 'next/document';
import React from 'react';

class CustomDocument extends Document {
  render() {
    return (
      <Html style={{ height: '100%' }}>
        <Head>
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        </Head>
        <body style={{ height: '100%', overflow: 'hidden' }}>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

// Import the getInitialProps method and assign it to your component to ensure the react-native-web styles are used.
CustomDocument.getInitialProps = getInitialProps;

export default CustomDocument;

```

There are two issues I found with this:

1. "Select" components running in android native throw an error: `TypeError: undefined is not an object (evaluating 'props.getItem')`
2. "Input" components inside of Modals running in next.js behave weird if I enter text on my phone. E.g. enter "student" in the Input, press the auto-completion for "students" and you get "studentstudents" while it should be just "students"

**Comment by JaccoGoris** [comment]
Is there any news on this? I'm trying to setup a project with the latest next (example template app is outdated) and native base 3.14.8 it's breaking a lot still :/

**Comment by Viraj-10** [comment]
Hi All, for `next 12.2` and `react 18.2` support please update your native-base package to `v3.4.19`.
Replace your `_document.js` with the following code.
```
import React, { Children } from "react";
import NextDocument, { Html, Head, Main, NextScript } from "next/document";
import { AppRegistry } from "react-native-web";
import { getStyleElement as getResponsiveQueryStyleElement } from "native-base";
// Force Next-generated DOM elements to fill their parent's height
const normalizeNextElements = `
  html, body, #__next {
    width: 100%;
    /* To smooth any scrolling behavior */
    -webkit-overflow-scrolling: touch;
    margin: 0px;
    padding: 0px;
    /* Allows content to fill the viewport and go beyond the bottom */
    min-height: 100%;
  }
  #__next {
    flex-shrink: 0;
    flex-basis: auto;
    flex-direction: column;
    flex-grow: 1;
    display: flex;
    flex: 1;
  }
  html {
    scroll-behavior: smooth;
    -webkit-text-size-adjust: 100%;
    height: 100%;
  }
  body {
    display: flex;
    overflow-y: auto;
    overscroll-behavior-y: none;
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    -ms-overflow-style: scrollbar;
  }
`;

export async function getInitialProps({ renderPage }) {
  AppRegistry.registerComponent("Main", () => Main);
  const { getStyleElement } = AppRegistry.getApplication("Main");
  const page = renderPage();
  const styles = [
    // eslint-disable-next-line react/jsx-key
    <style dangerouslySetInnerHTML={{ __html: normalizeNextElements }} />,
    getStyleElement(),
    getResponsiveQueryStyleElement(),
  ];
  return { ...page, styles: Children.toArray(styles) };
}
class Document extends NextDocument {
  render() {
    return (
      <Html>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
export default Document;

```

**Comment by lobor** [comment]
same here, see this repo for reproductible step
https://github.com/lobor/nativebase-nextjs

**Comment by lobor** [comment]
I found a workaround.
The problem is server side renderer (SSR), so load `NativeBaseProvider` in browser and not in server

```typescript 
// _app.tsx
import "../styles/globals.css";
import React, { useEffect, useState } from "react";
import { NativeBaseProvider } from "native-base";

function MyApp({ Component, pageProps }) {
  const [state, setState] = useState(false);
  useEffect(() => {
    if (typeof window !== "undefined" && !state) {
      setState(true);
    }
  }, []);
  return state ? (
    <NativeBaseProvider>
      <Component {...pageProps} />
    </NativeBaseProvider>
  ) : null;
}

export default MyApp;
```

**Comment by Viraj-10** [comment]
Hi @lobor, you need to pass `isSSR` prop to `NativeBaseProvider`.

**Comment by lobor** [comment]
I have same error with isSSR

**Comment by benmoses-equineregister** [comment]
I managed to workaround this by installing @expo/config in my repo, e.g. `yarn add @expo/config` so I'm guessing `@expo/next-adapter` is missing that as a dependency?

**Comment by cgorrieri** [comment]
> I found a workaround. The problem is server side renderer (SSR), so load `NativeBaseProvider` in browser and not in server
> 
> ```ts
> // _app.tsx
> import "../styles/globals.css";
> import React, { useEffect, useState } from "react";
> import { NativeBaseProvider } from "native-base";
> 
> function MyApp({ Component, pageProps }) {
>   const [state, setState] = useState(false);
>   useEffect(() => {
>     if (typeof window !== "undefined" && !state) {
>       setState(true);
>     }
>   }, []);
>   return state ? (
>     <NativeBaseProvider>
>       <Component {...pageProps} />
>     </NativeBaseProvider>
>   ) : null;
> }
> 
> export default MyApp;
> ```

This is not a real workaround as it will prevent any SSR. Why use NextJs in that case?

**Comment by lobor** [comment]
I use Nextjs for the easy configuration. it's very simple, not created router, wrapper, ... all in one. SEO in not a problem

we have chosen [tamagui](https://github.com/tamagui/tamagui) for design system, more light, ssr compatible and more simple
