### ISSUE TITLE
A warning thrown with jest 

### ISSUE THREAD

**Issue by tmhao2005** [GeekyAnts/NativeBase#5371]
### Description

There was a warning thrown as we ran test as following: `TypeError: _reactNative.AppState.removeEventListener is not a function`

### CodeSandbox/Snack link

https://codesandbox.io/s/codesandbox-sse-example-forked-izm8zv?file=/sample.test.jsx

### Steps to reproduce

1. Visit the above codesanbox
2. Run `yarn test` command then you will the see the warning

### NativeBase Version

3.4.15

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by ahilles107** [comment]
my stack trace for this issue
```
    console.error
      Warning: Internal React error: Attempted to capture a commit phase error inside a detached tree. This indicates a bug in React. Likely causes include deleting the same fiber more than once, committing an already-finished tree, or an inconsistent return pointer.

      Error message:

      TypeError: _reactNative.AppState.removeEventListener is not a function
          at HybridProvider (/Users/pmikolajczuk/Projects/priv/koncept-bobo/asystentciazy/node_modules/native-base/lib/commonjs/core/hybrid-overlay/HybridProvider.tsx:9:3)
          at ResponsiveQueryProvider (/Users/pmikolajczuk/Projects/priv/koncept-bobo/asystentciazy/node_modules/native-base/lib/commonjs/utils/useResponsiveQuery/ResponsiveQueryProvider.tsx:20:12)
          at RNCSafeAreaProvider
          at Component (/Users/pmikolajczuk/Projects/priv/koncept-bobo/asystentciazy/node_modules/react-native/jest/mockNativeComponent.js:17:18)
          at SafeAreaProvider (/Users/pmikolajczuk/Projects/priv/koncept-bobo/asystentciazy/node_modules/react-native-safe-area-context/lib/commonjs/SafeAreaContext.tsx:35:3)
          at Provider (/Users/pmikolajczuk/Projects/priv/koncept-bobo/asystentciazy/node_modules/native-base/lib/commonjs/utils/createContext.tsx:9:13)
          at NativeBaseProvider (/Users/pmikolajczuk/Projects/priv/koncept-bobo/asystentciazy/node_modules/native-base/lib/commonjs/core/NativeBaseProvider.tsx:52:5)
          at TestingNativeBaseProvider (/Users/pmikolajczuk/Projects/priv/koncept-bobo/asystentciazy/tests/ui/TestingNativeBaseProvider.tsx:5:3)
```

**Comment by devpgcs** [comment]
Same issue when updating from version`^3.4.12` to `^3.4.16`.

**Comment by ankit-tailor** [comment]
Hey everyone, Thanks for reporting the issue. We'll fix it.

**Comment by MateuszRostkowski** [comment]
Hey guys, I've created temporary patch for this issue:

File: `/patches/native-base+3.4.16.patch`

```patch
diff --git a/node_modules/native-base/lib/commonjs/core/color-mode/hooks.js b/node_modules/native-base/lib/commonjs/core/color-mode/hooks.js
index 8e28efe..68490c8 100644
--- a/node_modules/native-base/lib/commonjs/core/color-mode/hooks.js
+++ b/node_modules/native-base/lib/commonjs/core/color-mode/hooks.js
@@ -45,9 +45,9 @@ const useAppState = () => {
   const subscription = _react.default.useMemo(() => ({
     getCurrentValue: () => _reactNative.AppState.currentState,
     subscribe: callback => {
-      _reactNative.AppState.addEventListener('change', callback);
+      const sb = _reactNative.AppState.addEventListener('change', callback);
 
-      return () => _reactNative.AppState.removeEventListener('change', callback);
+      return () => sb.remove()
     }
   }), []);
```

After next release, just delete this patch.

**Comment by austinrbrown01** [comment]
Getting the same error here when running tests with Jest

`console.error
    Warning: Internal React error: Attempted to capture a commit phase error inside a detached tree. This indicates a bug in React. Likely causes include deleting the same fiber more than once, committing an already-finished tree, or an inconsistent return pointer.

    Error message:

    TypeError: _reactNative.AppState.removeEventListener is not a function
        at children (C:\Users\duder\Desktop\School\Fall 22\CSE 485\MobileAppRepo\mobile-app\node_modules\native-base\lib\commonjs\core\hybrid-overlay\HybridProvider.tsx:9:3)
        at disableCSSMediaQueries (C:\Users\duder\Desktop\School\Fall 22\CSE 485\MobileAppRepo\mobile-app\node_modules\native-base\lib\commonjs\utils\useResponsiveQuery\ResponsiveQueryProvider.tsx:20:12)
        at RNCSafeAreaProvider
        at RNCSafeAreaProvider (C:\Users\duder\Desktop\School\Fall 22\CSE 485\MobileAppRepo\mobile-app\node_modules\react-native\jest\mockNativeComponent.js:17:18)
        at children (C:\Users\duder\Desktop\School\Fall 22\CSE 485\MobileAppRepo\mobile-app\node_modules\react-native-safe-area-context\lib\commonjs\SafeAreaContext.tsx:35:3)
        at children (C:\Users\duder\Desktop\School\Fall 22\CSE 485\MobileAppRepo\mobile-app\node_modules\native-base\lib\commonjs\utils\createContext.tsx:9:13)
        at colorModeManager (C:\Users\duder\Desktop\School\Fall 22\CSE 485\MobileAppRepo\mobile-app\node_modules\native-base\lib\commonjs\core\NativeBaseProvider.tsx:52:5)`

**Comment by maaliHasan** [comment]
I'm using native-base version 3.4.19 and still have the issue! Any updates on this?

**Comment by bebe84** [comment]
Yes, got the same error, please fix it 🙏

**Comment by dhcmega** [comment]
Hi
The problem is still there but it has moved to a different file? Using 3.4.25

`%s%s, TypeError: react_native_1.Dimensions.removeEventListener is not a function. (In 'react_native_1.Dimensions.removeEventListener('change', onChange)', 'react_native_1.Dimensions.removeEventListener' is undefined), 
    in CheckinScreen (created by Screens)`

`node_modules/native-base/src/utils/useResponsiveQuery/common.ts`

```ts
// The below implementation is taken from React Native's source and added a flag to conditionally attach/remove listeners
export const useDimensionsWithEnable = ({ enable }: { enable?: boolean }) => {
  const [dimensions, setDimensions] = React.useState(() =>
    Dimensions.get('window')
  );

  React.useEffect(() => {
    if (enable) {
      function handleChange({ window }: { window: ScaledSize }) {
        if (
          dimensions.width !== window.width ||
          dimensions.height !== window.height ||
          dimensions.scale !== window.scale ||
          dimensions.fontScale !== window.fontScale
        ) {
          setDimensions(window);
        }
      }
      Dimensions.addEventListener('change', handleChange);
      // We might have missed an update between calling `get` in render and
      // `addEventListener` in this handler, so we set it here. If there was
      // no change, React will filter out this update as a no-op.
      handleChange({ window: Dimensions.get('window') });

      return () => {
        Dimensions.removeEventListener('change', handleChange);  //  <- HERE! ####################
      };
    }
    return () => {};
  }, [dimensions, enable]);
  return dimensions;
};
```

**Comment by r3dm1ke** [comment]
Version `3.4.28` still has this bug:
```
 console.error
    Warning: Internal React error: Attempted to capture a commit phase error inside a detached tree. This indicates a bug in React. Likely causes include deleting the same fiber more than once, committ
ing an already-finished tree, or an inconsistent return pointer.
    
    Error message:
    
    TypeError: Cannot read properties of undefined (reading 'remove')
        at HybridProvider (C:\personal_projects\clean-gta-clients\node_modules\native-base\lib\commonjs\core\hybrid-overlay\HybridProvider.tsx:9:3)
        at ResponsiveQueryProvider (C:\personal_projects\clean-gta-clients\node_modules\native-base\lib\commonjs\utils\useResponsiveQuery\ResponsiveQueryProvider.tsx:20:12)
        at RNCSafeAreaProvider
        at Component (C:\personal_projects\clean-gta-clients\node_modules\react-native\jest\mockNativeComponent.js:17:18)
        at SafeAreaProvider (C:\personal_projects\clean-gta-clients\node_modules\react-native-safe-area-context\src\SafeAreaContext.tsx:35:3)
        at Provider (C:\personal_projects\clean-gta-clients\node_modules\native-base\lib\commonjs\utils\createContext.tsx:9:13)
        at NativeBaseProvider (C:\personal_projects\clean-gta-clients\node_modules\native-base\lib\commonjs\core\NativeBaseProvider.tsx:52:5)

```

**Comment by joaosousafranco** [comment]
Same here but with the badge component, im doing the following:

`
const TestComponent = (props: Record<string, unknown>) => <View {...props} />

jest.mock('native-base', () => ({
  ...jest.requireActual('native-base'),
  HamburgerIcon: () => <TestComponent testID="menu-icon" />,
  AddIcon: () => <TestComponent testID="add-icon" />,
}))
`

**Comment by ammanvedi** [comment]
Came across this and same issue as @joaosousafranco 

```
jest.mock('native-base', () => {
  console.log(jest.requireActual('native-base'))
  return {
    ...jest.requireActual('native-base'),
    Collapse: (props: ICollapseProps) => {
      if (props.isOpen) {
        props.onAnimationEnd?.()
      }
      return props.isOpen ? props.children : null
    },
  }
})
```


```
TypeError: Cannot read properties of undefined (reading 'Badge')
```
