### ISSUE TITLE
Memory Leak : HybridProvider 

### ISSUE THREAD

**Issue by MarkLester10** [GeekyAnts/NativeBase#5547]
### Description

When you close the app there is a memory leak in useEffect HybridProvider: 

### CodeSandbox/Snack link

/

### Steps to reproduce

1. Open the app
2. Close
3. Error in Metro appears
```
ERROR Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
in HybridProvider (at NativeBaseProvider.tsx:90)
```

### NativeBase Version

3.4.5

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

Project is using RN 0.68.2

**Comment by surajahmed** [comment]
@MarkLester10 Thanks for reporting.
We'll look into this. Hope to fix this in the coming release.

**Comment by kevindice** [comment]
Pretty sure I'm seeing the same issue but with a slightly different message:
```
    console.error
      Warning: Internal React error: Attempted to capture a commit phase error inside a detached tree. This indicates a bug in React. Likely causes include deleting the same fiber more than once, committing an already-finished tree, or an inconsistent return pointer.
      
      Error message:
      
      TypeError: Cannot read properties of undefined (reading 'remove')
          at children (/Users/kdice/company-redacted/mobile-apps/node_modules/native-base/lib/commonjs/core/hybrid-overlay/HybridProvider.tsx:9:3)
          at disableCSSMediaQueries (/Users/kdice/company-redacted/mobile-apps/node_modules/native-base/lib/commonjs/utils/useResponsiveQuery/ResponsiveQueryProvider.tsx:20:12)
          at children (/Users/kdice/company-redacted/mobile-apps/node_modules/react-native-safe-area-context/jest/mock.js:26:24)
          at children (/Users/kdice/company-redacted/mobile-apps/node_modules/native-base/lib/commonjs/utils/createContext.tsx:9:13)
          at colorModeManager (/Users/kdice/company-redacted/mobile-apps/node_modules/native-base/lib/commonjs/core/NativeBaseProvider.tsx:52:5)
```

Fills up the Jest output quite a bit.

**Comment by reactionic127** [comment]
@surajahmed Is there any updates about this issue? I am having same issue in Jest.
My issue is same with @kevindice

**Comment by bojackhorseman0309** [comment]
I'm having the same issue like @kevindice when running my tests after updating to Expo SDK 46, also using latest Native Base.

Is this already fixed? Did someone found anything?

**Comment by kevindice** [comment]
My team has been using a yarn patch on it so far:

![Screenshot_20230319-140112.png](https://user-images.githubusercontent.com/5779569/226205813-2513ab41-9880-4096-992b-21e3676aa457.png)

(apologies for the screenshot, am on mobile)

**Comment by bojackhorseman0309** [comment]
@kevindice Ohhhh yeah indeed, just did a quick change on the file and it indeed doesn't show anymore. Thanks for the quick response.

I saw that you reviewed this PR that introduce that code https://github.com/GeekyAnts/NativeBase/pull/5359

If the fix is to use the optional chaining, why it hasn't been done? Is there a more deeper issue with this? Or is it that it just haven't been done?

**Comment by kevindice** [comment]
> @kevindice Ohhhh yeah indeed, just did a quick change on the file and it indeed doesn't show anymore. Thanks for the quick response.
> 
> I saw that you reviewed this PR that introduce that code https://github.com/GeekyAnts/NativeBase/pull/5359
> 
> If the fix is to use the optional chaining, why it hasn't been done? Is there a more deeper issue with this? Or is it that it just haven't been done?

Honestly not sure

**Comment by kevindice** [comment]
> @kevindice Ohhhh yeah indeed, just did a quick change on the file and it indeed doesn't show anymore. Thanks for the quick response.
> 
> I saw that you reviewed this PR that introduce that code https://github.com/GeekyAnts/NativeBase/pull/5359
> 
> If the fix is to use the optional chaining, why it hasn't been done? Is there a more deeper issue with this? Or is it that it just haven't been done?

Honestly not sure

**Comment by r3dm1ke** [comment]
Is there an update for this one? Can I open a PR that adds optional chaining?

**Comment by bojackhorseman0309** [comment]
Not at all, I created my tests around not triggering this, but it's still there.
________________________________
