### ISSUE TITLE
_reactNative.Keyboard.addListener is not a function

### ISSUE THREAD

**Issue by dharmveer-say-aloha** [GeekyAnts/NativeBase#5663]
### Description

I am using jest testing in my react native, getting this below error whenever I run testing 

### CodeSandbox/Snack link

NA

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

3.4.25

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Other Platform

NA

### Additional Information

TypeError: _reactNative.Keyboard.addListener is not a function
    at /Users/siddhantbansal/Documents/Projects/ReactApp/React Native/coreapp/node_modules/native-base/lib/commonjs/utils/useKeyboardBottomInset.ts:24:18
    at commitHookEffectListMount (/Users/siddhantbansal/Documents/Projects/ReactApp/React Native/coreapp/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12423:26)
    at commitPassiveMountOnFiber (/Users/siddhantbansal/Documents/Projects/ReactApp/React Native/coreapp/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13822:11)
    at commitPassiveMountEffects_complete (/Users/siddhantbansal/Documents/Projects/ReactApp/React Native/coreapp/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13781:9)
    at commitPassiveMountEffects_begin (/Users/siddhantbansal/Documents/Projects/ReactApp/React Native/coreapp/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13768:7)
    at commitPassiveMountEffects (/Users/siddhantbansal/Documents/Projects/ReactApp/React Native/coreapp/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13756:3)
    at flushPassiveEffectsImpl (/Users/siddhantbansal/Documents/Projects/ReactApp/React Native/coreapp/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15675:3)
    at flushPassiveEffects (/Users/siddhantbansal/Documents/Projects/ReactApp/React Native/coreapp/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15633:14)
    at /Users/siddhantbansal/Documents/Projects/ReactApp/React Native/coreapp/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15459:9
    at workLoop (/Users/siddhantbansal/Documents/Projects/ReactApp/React Native/coreapp/node_modules/scheduler/cjs/scheduler.development.js:266:34)

**Comment by alok-sse** [comment]
facing same issue
