### ISSUE TITLE
TypeError: Cannot read property 'displayName' of undefined

### ISSUE THREAD

**Issue by iegik** [GeekyAnts/NativeBase#824]
```
    "react-native": "0.44.0",
    "native-base": "^2.1.3",
    "react": "~15.4.0",
```

Got error after running jest tests, after importing `native-base`
```
import { StyleProvider } from 'native-base/backward';
```

```
TypeError: Cannot read property 'displayName' of undefined
      
      at getComponentDisplayName (node_modules/native-base-shoutem-theme/src/connectStyle.js:86:24)
      at wrapWithStyledComponent (node_modules/native-base-shoutem-theme/src/connectStyle.js:90:26)
      at Object.<anonymous> (node_modules/native-base-shoutem-theme/examples/Shapes.js:128:68)
      at Object.<anonymous> (node_modules/native-base-shoutem-theme/index.js:6:13)
```

package.json#jest

```
  "jest": {
    "preset": "react-native",
    "setupFiles": [
      "<rootDir>/.jest"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|react-clone-referenced-element|native-base|@shoutem)"
    ],
    "collectCoverage": true,
    "verbose": true
  }
```

Also installed:
```
    "@expo/vector-icons": "^4.0.0",
    "@shoutem/theme": "^0.9.0",
...
    "react-native-vector-icons": "^4.1.1",
```

NPM warnings:
```
pm WARN native-base@2.1.3 requires a peer of react@>=16.0.0-alpha.3 but none was installed.
npm WARN native-base@2.1.3 requires a peer of react-native-vector-icons@~4.0.0 but none was installed.
npm WARN react-addons-shallow-compare@15.4.2 requires a peer of react@^15.4.2 but none was installed.
npm WARN react-dom@15.5.4 requires a peer of react@^15.5.4 but none was installed.
npm WARN react-native@0.44.0 requires a peer of react@16.0.0-alpha.6 but none was installed.
npm WARN react-native-elements@0.11.2 requires a peer of react-native-vector-icons@~4.0.0 but none was installed.
npm WARN react-native-qrcode-svg@4.0.1 requires a peer of react@^15.4.2 but none was installed.
npm WARN react-native-qrcode-svg@4.0.1 requires a peer of react-native@^0.42.0 but none was installed.
npm WARN react-native-svg@5.1.8 requires a peer of react@16.0.0-alpha.6 but none was installed.
npm WARN react-qr-code@0.1.1 requires a peer of react@~15.3.2 but none was installed.
npm WARN react-qr-code@0.1.1 requires a peer of react-dom@~15.3.2 but none was installed.
npm WARN react-qr-code@0.1.1 requires a peer of react-native@^0.38.0 but none was installed.
npm WARN react-test-renderer@15.5.4 requires a peer of react@^15.5.0 but none was installed.
```

index.js
```
import React, { Component } from 'react';
import { StyleProvider } from 'native-base/backward';
import getTheme from '../native-base-theme/components';
export default class App extends Component {
    render() {
        return (
            <StyleProvider style={getTheme()} >
            </StyleProvider>
        );
    }
}
```

**Comment by SupriyaKalghatgi** [comment]
@iegik Can you check with the latest versions?
```
"native-base": "2.1.4",
"react": "16.0.0-alpha.6",
"react-native": "0.44.0"
```

**Comment by SupriyaKalghatgi** [comment]
Closing this issue due to inactivity

**Comment by iegik** [comment]
Sorry, cannot check this right now. I`ll answer this later.
